### ISSUE TITLE
Alphabetical sorting in WriteNextLine

### ISSUE THREAD

**Issue by grlbrwrg** [ArjenLammers/csv-connector#10]
First of all, thanks for creating this module! I was wondering why the "attributes" array is being sorted before writing the line. I tried commenting the line out and was able to preserve the column structure based on the original entity, which would be preferred in my use case. Are there any edge cases I might have missed here?

https://github.com/ArjenLammers/csv-connector/blob/ef2f9957804892c6dfd75188d09b89c2d0b0b22d/javasource/csv/actions/WriteNextLine.java#L71

**Comment by ArjenLammers** [comment]
hi @grlbrwrg , thanks for this issue.
by the time this module was created, the order of attributes returned by the Core API did not match the order of definition in the model which led to very unpredictable behavior.
in the meantime it seems that the underlying implementation has changed this might be more predictable now and I think it can be changed (removed and rely on the list of attributes changed).

however, changing this should be done with care (making very very very sure it works this way in the recent Mendix versions and check since when this predictable order is there) before making a next release.

unfortunately I don't have a lot of time on my hands to do this, but I will keep this issue open.

**Comment by ArjenLammers** [comment]
The sorting will be removed in the next version as the order of declaration is now reflected in the Java API.
