### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by steviesteve** [ArjenLammers/csv-connector#4]
Hi 

We are wondering if adding a date format for date fields on export would be good idea going forward. Think currently timestamps get outputted

We could work on a pull request if that is something that would be helpful so you could pass a date format to java actions for exporting CSV's

S

**Comment by ArjenLammers** [comment]
hi steviesteve,

I'm not sure which export you're talking about. If you're using the actions to write line by line, you will have all flexibility within a microflow. Using SQL you could use database specific date/time formatting. Only OQL would be limited to timestamps I guess; because I don't see date/time formatting functions documented.

Kind regards,
Arjen

**Comment by steviesteve** [comment]
Hi

Yes oql would be where this is most useful

S

**Comment by ArjenLammers** [comment]
I understand the need, but the implementation would be quite some work. Being able to influence date/time formatting would include timestamp/text. But within the text there's formatting and localization. Probably it should also be configurable per column. It would make the module very complex.
I would suggest the one of the following approaches:
 - Create an attribute which has the value you want to export (if localization is not involved).
 - Use the export line by line approach and format within your microflow.

**Comment by steviesteve** [comment]
Thanks good suggestions
