### ISSUE TITLE
[Feature request] Enabling Export(OQL/SQL)ToCSV to Specify the Date Format.

### ISSUE THREAD

**Issue by a-takashima-k** [ArjenLammers/csv-connector#6]
Currently, attribute of type Datetime are output as numerical timestamps in ExportOQLToCSV and ExportSQLToCSV.
In most cases, the time is displayed as a formatted string rather than a number.
The format also depends on the country where it is used.

I think this is a good thing for the convenience.

**Comment by ArjenLammers** [comment]
hi a-takashima-k,

I do understand your need, but this goes beyond the scope of the module.
A timestamp is convenient because it's independent of timezones and formatting and is excellent for system-to-system integration.

However, you can achieve similar functionality by:
- Add a String attribute in the entity and set its value (e.g. using before commit event), and use this during your export.
- Leverage date formatting functions of the database (if using the SQL approach).
- Use the connector-style export action (and write line by line where you use a NPE to format).

Kind regards,
Arjen Lammers
